proxy:
  secretToken: "b8a837e2d4400514f6abff16d1c79492dbce237714299b40624c90f97dccc0d4"  
  service:
    type: ClusterIP  
    
hub:
  baseUrl: /test-jhub
  db:
    pvc:
      storageClassName: local-path

singleuser:
  memory:
    limit: 1G
    guarantee: 1G

  cpu:
    limit: .5
    guarantee: .5

  storage:
    dynamic:
      storageClass: local-path
    capacity: 1Gi

  # Defines the default image
  defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
  image:
    name: jupyter/minimal-notebook
    tag: latest
  profileList:
    - display_name: "Minimal environment"
      description: "A Python environment."
      default: true
    - display_name: "Datascience environment"
      description: "Python, R and Julia environments."
      kubespawner_override:
        image: jupyter/datascience-notebook:latest
